/* Package: bearGameMerge
 * Class: Map
 * Programmer: ICS4U
 * Date Created: January , 2016
 * Description: Base map
 */

package bearGameMerge2;

public class Map {
	static String[] maze = {
			"OOOOOOOOOOOOOOOOOOOOOOOO",
			"OOOOOOOOOOOOOOOOOOOOOOOO",
			"OOOOOOOOOOOOOOOOOOOOOOOO",
			"OOOOOOOOOOOOOOOOOOOOOOOO",
			"OOOOOOOOOOOOOOOOOOOOOOOO",
			"OOOOOOOOOOOOOOOOOOOOOOOO",
			"OOOOOOOOOOOOOOOOOOOOOOOO",
			"OOOOOOOOOOOOOOOOOOOOOOOO",
			"OOOOOOOOOOOOOOOOOOOOOOOO",
			"OOOOOOOOOOOOOOOOOOOOOOOO",
			"OOOOOOOOOOOOOOOOOOOOOOOO"
			};
	static String[] mazeOne = { "TTCcAadTTTTTTTTTTTTTTT", "TTGGGGGGGGGGGGGGGGHTTT", "TGGGGGGGGGGGGGGGGGGGGG",
		"TGGGGGGGGGGGGGGGGGGGGG", "TGGGGGGGGGGGGGGGGGGGGG", "TGGGGGGGGGGGGGGGGGGGGG", "TGGGGGGGGGGGGGGGGGGGGG",
		"TTGGGGGGGGGGGGGGGGGGGG", "TTGGGGGGGGGGGGGGGGTTTT", "TTTTTGGGGGGGGGGGGTTTTT", "TTTTTGGGGGGGGGGGGTTTTT" };

static String[] mazeTwo = { "TTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTT", "GGGGGGGGGGGGHGGGGGGGTT",
		"GGGGGGGGBGGGGGGGBGGGGG", "GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGGGGGGGG",
		"GGGGGGGGGGGGGGGGGGGGGG", "TTTTGGGGGGGGGGGGGGGGGT", "TTTTTGGGGGGGGGGGGGGTTT", "TTTTTTTGGGGGGGGGGTTTTT" };

static String[] mazeThree = { "TTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTT", "TTGGGGGGGGGGGGGHGTTTTT",
		"GGGGGGGGBGGGGGGGBGGTTT", "GGGGGGGGGGGGGGGGGGGGTT", "GGGGGGGGGGGGGGGGGGGGTT", "GGGGGGGGGGGGGGGGGGGGTT",
		"GGGGGGGGGGGGGGGGGGGGGT", "TTGGGGGGGGGGGGGGGGGGGT", "TTGGGGGGGGGGGGGGGGGGGT", "TTTTTTTTTTGGGGGGGGGGGT" };

static String[] mazeFour = { "TTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTGGGGGGGGG", "TTTTTTTTGGGHGGGGGGGGGG",
		"TTTTTTGGGDGGGGGGBGGGGG", "TTTTTGGGGGGGGGGGGGGGGG", "TTTTGGGGGGGGGGGGGGGGGG", "TTTTGGGGGGGGGGGGGGGGGG",
		"TTTGGGGGGGGGGGGGGGGGGG", "TTTGGGGGGGGGGGGGGGGBGT", "TTGGGGGGGGGGGGGGGGGGTT", "TGGGGGGGGGGGGGGGGGGTTT" };

static String[] mazeFive = { "TTTTTTTTTTTTTTTTTTTTTT", "GGGGGGGGGGHGGGGGTTTTTT", "GGGGGBGGGGGGGGGGGGTTTT",
		"GGGGGGGGGGBGGGGGBGGGTT", "GGGGGGGGGGGGGGGGGGGGGT", "GGGGGGGGGGGGGGGGGGBGGT", "GGGGGGGGGGGGGGGGGGGGGT",
		"GGGGGGGGGGGGGGGGGGGGGT", "TGGGGGGGGGGGGGGGGGGGGT", "TTGGBGGGGGGGGGGGGGGBGT", "TTTTTTTTTTTTTTTTTTTTTT" };

static String[] mazeSix = { "TTTTTGGGGGGGGGGGGTTTTT", "TTTTTGGGGGGGGGGGGTTTTT", "TTTTTGGGGGGGGGGGGTTTTT",
		"TTTTTGGGGGGGGGGGGBTTTT", "TTTTTGGGGGGGGGGGGGGGTT", "TTTTTGGGGGGGGGGGGGGGGG", "TTTTTTGGGGGGGGGGGGGGGG",
		"TTTTTTGGGGGGGGGGGGGGGG", "TTTTTTTGGGGGGGGGGGHGGG", "TTTTTTTGGGGGGGGGGGTTGG", "TTTTTTTTGGGGGGGTTTTTTT" };

static String[] mazeSeven = { "TTTTTTTGGGGGGGGGGTTTTT", "TTTTTTTGGGGGGGGGGGTTTT", "TTTTTGGGGGGGGGGGGGGTTT",
		"TTTTHGGGGGGGGGGGGGGHTT", "TTTGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGGGGGGGG",
		"GGGGGGGGGGGGGGGGGTTGGG", "GGGGGGTTTGGGGGGGTTTTTT", "GGGGTTTTGGGGGGTTTTTTTT", "TTTTTTTTGGGGGGTTTTTTTT" };

static String[] mazeEight = { "TTTTTTTTTTGGGGGGGGGGGT", "TTTTTTGGGGGGGGGGGGGGGG", "TTTTGGGGGGGGGGGGGGGGGG",
		"TTGGGGGGGGGTTTBGGGGGGG", "GGGGGGGGTTTTTTTTTTGGGG", "GGGGGGGTTTTTTTTTTTGGGG", "GGGGGGGGGGTTTTTTGGGGGG",
		"GGGGGGGGGGGGGGGGGGGGGG", "TGGGGGGGGGGGGGGGDGGGGG", "TTTGGHGGGGGGGGGGGGGGGG", "TTTTTTGGGGGGGGGGGGGGTT" };

static String[] mazeNine = { "TGGGGGGGGGGGGGGGGGGTTT", "GGGGGGGGGGGGGGGGGGTTTT", "GGGGGGGGGGGGGGGGGGBTTT",
		"GGGGGGGGGGGGGGGGGGGGTT", "GGGGGGGGGGGGHGGGGGGGGG", "GGGGGGGGGGGTTTGGGGGGGG", "GGGGGGBGGTTTTTTTGGGGGG",
		"GGGGTTTTTTTTTTTTTTTGGG", "GGGTTTTTTTTTTTTTTTTTGG", "GGTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTT" };

static String[] mazeTen = { "TTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTT", "TTTTTGGBGGGGHGGGGTTTTT",
		"TTTTTTGGGGGGGGGGGGGTTT", "GTTTTTGGGGGGGGGGGGGTTT", "GGTTTGGGGGGGGGGGGGGTTT", "GGGGGGGGGGGGGGGGGGBTTT",
		"GGGGGGGGGGGGGGGGGGGGTT", "GTTTTGGGGGGGGGGGGGGGTT", "TTTTTTGGGGGGGGGGGGGGTT", "TTTTTTGGGGGGGGGGGGGGGT" };

static String[] mazeEleven = { "TTTTTTTTGGGGGGGTTTTTTT", "TTTTGGGHGGGGGGGGTTTTTG", "TTTGGGGGGGGGGGGGGTTGGG",
		"TTGGGGGGGGGGGGGGGGGGGG", "TTGGGGGGGGGGGGGGGGGGGG", "TTGGGGGGGGGGGGGGGGGGGG", "TTTGGGGGGGGGGGGGGGGGGG",
		"TTTTGGGGGGGGGGGGGGGGGG", "TTTTTTGGGGGGGGGGGGGGGG", "TTTTTTTTTTBGGGHGGGGGGG", "TTTTTTTTTTTTTTTTTTTTTT" };

static String[] mazeTwelve = { "TTTTTTTTGGGGGGTTTTTTTT", "GGGGHGGGGGGGGGGGGGGHGG", "GGGGGGGGGGGGGGGGGGGGGG",
		"GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGTTGGGGGGGGGG", "GGGGGGGGGTTTTGGGGGGGGG",
		"GGGGGGGTTTTTTTTBGGGGGG", "GGGGBTTTTTTTTTTTTGGGGG", "GGGGTTTTTTTTTTTTTTGGGG", "TTTTTTTTTTTTTTTTTTTTTT" };

static String[] mazeThirteen = { "TTTTTTGGGGGGGGGGGGGGTT", "GGTTTTTGGGGGGGGGGGGGTT", "GGGGTTTTTGGGGGGGGGGTTT",
		"GGGGGGGTTTTBGGGGGGTTTT", "GGGGGGGGGGGGGGGGTTTTTT", "GGGGGGGGDGGGGGGGTTTTTT", "GGGGGGGGGGGGGGGGGGGGGG",
		"GGGGGGGGGGGGGGGGGGGGGG", "GGGHGGGGGGGGGGGGBTTTTT", "GTTTTTTBGGGGGGGGTTTTTT", "TTTTTTTTGGGGGGGTTTTTTT" };
static String[] mazeFourteen = { "TTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTG", "TTTTTTTTTTTTTTTTTTTTGG",
		"TTTTTTTTTTTTTTTTTTGGGG", "TTTTTTTTTTTTTTTTGGGGGG", "TTTTTTTTTTTTTTGGGGGGGG", "GGGGGGGGGHGGGGGGGGGGTT",
		"GGGGGGGGGGGGGGGGGGGTTT", "TTTTBGGGGGGGGGGGGGTTTT", "TTTTTGGGGGGGGGGGBTTTTT", "TTTTTTGGGGGGGGGGTTTTTT" };

static String[] mazeFifteen = { "TTTTTTGGGGGGGGGGGGGGGT", "GGHGGGGGGGGGGGGGGGGGGT", "GGGGGGGGGGGGGGGGGGGGGT",
		"GGGGGGGGGGGGGGGGGGGGTT", "GGGGGGGGGGGGGGGGGGGGTT", "GGGGGGGGGGGGGGGGGGTTTT", "TTGGGGGGGGGGGGGGGGBTTT",
		"TTTTGGGGGGGGGGGGGTTTTT", "TTTTTHGGGGGGGGGGGTTTTT", "TTTTTTGGGGGGGGGGTTTTTT", "TTTTTTTGGGGGGGGTTTTTTT" };

static String[] mazeSixteen = { "TTTTTTTTTTTTTTTTTTTTTT", "TGGGGGGTTTTTTTTTTTTGGG", "TGGGGGGGGGGGGGHGGGGGGG",
		"TGGGGGGGGGGGGGGGGGGGGG", "TGGGGGGGGGGGGGGGGGGGGG", "TGGGGGGGGGGGGGGGGGGGGG", "TGGGGGGGGGGGGGGGGGGGGG",
		"TGGGGGGGGGGGGGGGGGGGGG", "TGGGGGGGGGGGGGGGTTTTTT", "TGGGGGGGGGGGTTTTTTTTTT", "TGGGGGGGGGGTTTTTTTTTTT" };

static String[] mazeSeventeen = { "TTTTTTTTTTTTTTTTTTTTTT", "GGGGGGGBTTTTTTTTGGGGGG", "GGGGGGGGGGGGHGGGGGGGGG",
		"GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGGGGGGGG",
		"GGGGGGGGGGGGGGGGGGGGGG", "TTTGGGGGGGGGGGGGBTTTGG", "TTTTTGHGGGGGGGGTTTTTTT", "TTTTTTTTGGGGGGTTTTTTTT" };

static String[] mazeEighteen = { "TTTTTTTTGGGGGGGTTTTTTT", "GGGTTTTTGGGGGGGBTTTTTT", "GGGGGTTTGGGGGGGGGNXXvW",
		"GGGGGGHGGGGGGGGNXvWWWW", "GGGGGGGGGGNXXXXvWWWWWW", "GGGGGGGGGGVWWWWWWWWWWW", "GGGGGGGGGNvWWWWWWWWWWW",
		"GGGGGGGNXvWWWWWWWWWWWW", "GGGGGNXvWWWWWWWWWWWWWW", "TTGGNvWWWWWWWWWWWWWWWW", "TTTTTWWWWWWWWWWWWWWWWW" };

static String[] mazeNinteen = { "TTTTTTGGGGGGGGGGTTTTTT", "TGGGGGGGGGGGGGGGGGTTTT", "TXXXXXXXKGGGGGGGGGGHGT",
		"WWWWWWWWbXKGGGGGGGGGGG", "WWWWWWWWWWbKGGGGGGGGGG", "WWWWWWWWWWWbXKGGGGGGGG", "WWWWWWWWWWWWWbXXXXXXKG",
		"WWWWWWWWWWWWWWWWWWWWbX", "WWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWW" };

static String[] mazeTwenty = { "TTTTTTTGGGGGGGGTTTTTTT", "TTTTTTGGGGGGGGGGGGTTTT", "TTGGHGGGGGGGGGGGGGGGTT",
		"GGGGGGGGGGGGGNXXXXXXXT", "GGGGGGGGGGGGNvWWWWWWWW", "GGGGGGGGGGNXvWWWWWWWWW", "GGGGGGGGNXvWWWWWWWWWWW",
		"XXXXXXXXvWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWW" };

static String[] mazeTwentyOne = { "TGGGGGGGGGGTTTTTTTTTTT", "TGGGGGGGGGGTTTTTTTTTTT", "TGGGGGGBGGGGBTTTTTTTTT",
		"TGGGGGGGGGGGGGHGGTTTTT", "TTGGGGGGGGGGGGGGGGGGGG", "TTGGGGGGGGGGGGGGGGGGGG", "TTGGGGGGGGGGGGGGGGBGGG",
		"TTGGGGGGGGGGGGGGGGGGGG", "TTBGGGGGGGGGHGGGGGGGGG", "TTTTTTTTTTTTTTTTGGGGGG", "TTTTTTTTTTTTTTTTTTTTTT" };

static String[] mazeTwentyTwo = { "TTTTTTTTGGGGGGTTTTTTTT", "TTTTTTTTTGGGGGTTTTTTTT", "TTTTTGGBGGGGGGGGBTTTTT",
		"TTGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGGGGGGGG",
		"GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGHGGGGGGGGGG", "GGGGBTTTTTTTTTTGGGGGGG", "TTTTTTTTTTTTTTTTTTTTTT" };

static String[] mazeTwentyThree = { "TTTTTTWWWWWWWWWWWWWWWW", "TTTTTMzWWWWWWWWWWWWWWW",
		"TTTTTTMzWWWWWWWWWWWWWW", "GGGGGGGMZZZzWWWWWWWWWW", "GGGGGGGGGGGMZZzWWWWWWW", "GGTTTGGGGGGGGGMZZZZZZZ",
		"GGGGGGGGGGGGGGGGGGBGGG", "GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGHGGGGGGGGGGGGG", "GGTTTTTTTTTTTTTTTTGGGG",
		"TTTTTTTTTTTTTTTTTTTTTT" };

static String[] mazeTwentyFour = { "WWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWxZZZZZZZT",
		"WWWWWWxZZZZZZLGGGGGGGT", "WWxZZZLGGGGGGGGGGGGGGT", "ZZLGGGGGGGGGGGGGGGGGGT", "GGGGGGGGGGGGGGGGGGGGGT",
		"GGGGGGGGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGGGGGGGT", "GGGTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTT" };

static String[] mazeTwentyFive = { "WWWWWWWWWWWWWWWWWWWWWW", "WWWWWxZZZZZZZZzWWWWWWW", "ZZZZZLGGGGGGGGMZZZZzWW",
		"GGGGGGGGGGGGGGGGGGGMTT", "GGGGGGGGGGGGGGGGGGGGTT", "GGGGGGGGGGGGGGGGGGGGTT", "GGGGGGGGGGGGGGGGGGGGTT",
		"GGGGGGGGGGGGGGGGGGGGTT", "GGGGGGGGGGGGGGGGGGGGTT", "TTTTGGGGGGGGGGGGGGGTTT", "TTTTTTTTTTTTTTTTTTTTTT" };

}
